services:
  db:
    image: postgres:latest
    container_name: jd-database
    environment:
      POSTGRES_DB: encurtador
      POSTGRES_USER: jdarlan
      POSTGRES_PASSWORD: teste123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
